services:
  mongo:
    container_name: mongo_container
    image: mongo
    restart: always
    env_file: .env
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:rw
  

  mongo-express:
    container_name: mongo_express_container
    image: mongo-express
    restart: always
    env_file: .env
    depends_on:
      - mongo
    ports:
      - 8081:8081

  server:
    container_name: backend_server_container
    build:
      dockerfile: Dockerfile
      context: .
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - mongo

volumes:
  mongo-data:
